/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface": "#121414",
        "surfaceDim": "#121414",
        "surfaceBright": "#383939",
        "surfaceContainerLowest": "#0d0f0f",
        "surfaceContainerLow": "#1a1c1c",
        "surfaceContainer": "#1e2020",
        "surfaceContainerHigh": "#282a2a",
        "surfaceContainerHighest": "#333535",
        "primary": "#e9ddff",
        "onPrimary": "#342b4b",
        "primaryContainer": "#4b4163",
        "onPrimaryContainer": "#eaddff",
        "secondary": "#cbc2db",
        "onSecondary": "#332d41",
        "secondaryContainer": "#4a4458",
        "onSecondaryContainer": "#e8def8",
        "tertiary": "#efb8c8",
        "onTertiary": "#492532",
        "tertiaryContainer": "#633b48",
        "onTertiaryContainer": "#ffd8e4",
        "error": "#ffb4ab",
        "onError": "#690005",
        "errorContainer": "#93000a",
        "onErrorContainer": "#ffdad6",
        "background": "#121414",
        "onBackground": "#e2e2e2",
        "onSurface": "#e2e2e2",
        "onSurfaceVariant": "#c9c5d0",
        "outline": "#938f99",
        "outlineVariant": "#49454f",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#e2e2e2",
        "inverseOnSurface": "#2f3030",
        "inversePrimary": "#645a7c",
        "cyanCore": "#04fbfb",
        "cyanGlow": "#00dddd",
        // Additional settings tokens
        "on-primary": "#342c46",
        "on-tertiary-fixed": "#2c1700",
        "on-primary-fixed": "#1e1730",
        "secondary-fixed-dim": "#00dddd",
        "on-secondary": "#003737",
        "primary-fixed-dim": "#cdc1e2",
        "surface-bright": "#383939",
        "on-tertiary": "#492900",
        "on-secondary-fixed-variant": "#004f4f",
        "surface-variant": "#333535",
        "secondary-fixed": "#04fbfb",
        "on-primary-container": "#69607d",
        "surface-tint": "#cdc1e2",
        "secondary-container": "#04fbfb",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#683d00",
        "surface-container-highest": "#333535",
        "on-error": "#690005",
        "outline-muted": "#494454",
        "inverse-surface": "#e2e2e2",
        "surface-container-high": "#282a2a",
        "on-secondary-fixed": "#002020",
        "on-primary-fixed-variant": "#4b435e",
        "surface-container-low": "#1a1c1c",
        "tertiary-fixed-dim": "#ffb86a",
        "surface-low": "#1C1B1D",
        "outline-variant": "#49454d",
        "on-surface-variant": "#cac4cd",
        "tertiary-fixed": "#ffdcbc",
        "surface-high": "#2A2A2C",
        "error-container": "#93000a",
        "aether-purple": "#A078FF",
        "surface-dim": "#121414",
        "on-surface": "#e2e2e2",
        "on-secondary-container": "#007070",
        "primary-container": "#e9ddff",
        "primary-fixed": "#e9ddff",
        "on-surface-muted": "#CBC3D7",
        "surface-container-lowest": "#0d0f0f",
        "on-tertiary-container": "#8e580f",
        "on-background": "#e2e2e2",
        "inverse-on-surface": "#2f3131",
        "inverse-primary": "#635a76",
        "surface-container": "#1e2020",
        "tertiary-container": "#ffdcbb"
      },
      "spacing": {
        "section-gap": "160px",
        "margin-desktop": "40px",
        "section-gap-mobile": "80px",
        "gutter": "24px",
        "grid-unit": "40px",
        "element-stack": "16px",
        "margin-mobile": "16px",
        "unit": "4px",
        "orb-size-lg": "240px",
        "orb-size-sm": "48px",
        "container-padding": "2rem"
      },
      "fontFamily": {
        "body-md": ["'JetBrains Mono'", "monospace"],
        "display-xl-mobile": ["'JetBrains Mono'", "monospace"],
        "headline-lg-mobile": ["'JetBrains Mono'", "monospace"],
        "feature-title": ["'JetBrains Mono'", "monospace"],
        "display-xl": ["'JetBrains Mono'", "monospace"],
        "headline-lg": ["'JetBrains Mono'", "monospace"],
        "label-mono": ["'JetBrains Mono'", "monospace"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "body-lg": ["'JetBrains Mono'", "monospace"],
        // old tokens
        "headline-md-mobile": ["Geist", "sans-serif"],
        "metadata-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "geist": ["Geist", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-xl-mobile": ["40px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "feature-title": ["24px", { "lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "500" }],
        "display-xl": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "label-mono": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-lg": ["20px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "300" }],
        // old tokens
        "headline-md-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "metadata-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-caps": ["10px", { "lineHeight": "12px", "letterSpacing": "0.1em", "fontWeight": "700" }]
      },
      "backgroundImage": {
        'grid-pattern': 'linear-gradient(to right, #1a1c1c 1px, transparent 1px), linear-gradient(to bottom, #1a1c1c 1px, transparent 1px)',
        'blueprint-pattern': 'linear-gradient(to right, rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.03) 1px, transparent 1px)'
      },
      "animation": {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'orb-glow': 'orbGlow 3s ease-in-out infinite alternate',
        'orb-glow-intense': 'orbGlowIntense 2s ease-in-out infinite alternate',
        'orb-morph': 'orbMorph 8s ease-in-out infinite alternate',
        'orb-morph-slow': 'orbMorphSlow 15s ease-in-out infinite alternate',
        'sonar-pulse': 'sonarPulse 2s cubic-bezier(0, 0, 0.2, 1) infinite',
        'erratic-vibe': 'erraticVibe 0.5s linear infinite alternate',
        'ai-speech-pulse': 'aiSpeechPulse 0.8s ease-in-out infinite alternate',
      },
      "keyframes": {
        orbGlow: {
          '0%': { boxShadow: '0 0 40px 10px rgba(233, 221, 255, 0.2)' },
          '100%': { boxShadow: '0 0 80px 30px rgba(233, 221, 255, 0.5)' },
        },
        orbGlowIntense: {
          '0%': { boxShadow: '0 0 60px 20px rgba(233, 221, 255, 0.4)', transform: 'scale(0.95)' },
          '100%': { boxShadow: '0 0 120px 50px rgba(233, 221, 255, 0.8)', transform: 'scale(1.15)' },
        },
        aiSpeechPulse: {
          '0%': { transform: 'scale(0.9)', opacity: '0.8' },
          '100%': { transform: 'scale(1.1)', opacity: '1' },
        },
        sonarPulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(4, 251, 251, 0.7)' },
          '70%': { boxShadow: '0 0 0 40px rgba(4, 251, 251, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(4, 251, 251, 0)' },
        },
        erraticVibe: {
          '0%': { transform: 'scale(1) translate(0, 0)', boxShadow: '0 0 40px 10px rgba(4, 251, 251, 0.4)' },
          '25%': { transform: 'scale(1.02) translate(1px, -1px)', boxShadow: '0 0 50px 15px rgba(4, 251, 251, 0.6)' },
          '50%': { transform: 'scale(0.98) translate(-1px, 2px)', boxShadow: '0 0 30px 5px rgba(4, 251, 251, 0.3)' },
          '75%': { transform: 'scale(1.04) translate(-2px, -1px)', boxShadow: '0 0 60px 20px rgba(4, 251, 251, 0.7)' },
          '100%': { transform: 'scale(0.99) translate(1px, 1px)', boxShadow: '0 0 45px 12px rgba(4, 251, 251, 0.5)' },
        },
        orbMorph: {
          '0%': { borderRadius: '50% 50% 50% 50% / 50% 50% 50% 50%' },
          '25%': { borderRadius: '55% 45% 50% 50% / 50% 55% 45% 50%' },
          '50%': { borderRadius: '50% 55% 45% 55% / 55% 45% 55% 45%' },
          '75%': { borderRadius: '45% 50% 55% 45% / 50% 50% 45% 55%' },
          '100%': { borderRadius: '50% 50% 50% 50% / 50% 50% 50% 50%' },
        },
        orbMorphSlow: {
          "0%": { borderRadius: "50% 50% 50% 50% / 50% 50% 50% 50%", transform: "translate(0, 0) scale(1)" },
          "33%": { borderRadius: "55% 45% 50% 50% / 50% 55% 45% 50%", transform: "translate(2%, 2%) scale(1.05)" },
          "66%": { borderRadius: "50% 55% 45% 55% / 55% 45% 55% 45%", transform: "translate(-2%, -2%) scale(0.95)" },
          "100%": { borderRadius: "50% 50% 50% 50% / 50% 50% 50% 50%", transform: "translate(0, 0) scale(1)" }
        }
      }
    }
  },
  plugins: [],
}
